const scheduleData = {
    classes: ["V4A - MH"],
    periods: [
        { id: 0, time: "7:10 - 7:55" },
        { id: 1, time: "8:00 - 8:45" },
        { id: 2, time: "8:55 - 9:40" },
        { id: 3, time: "10:00 - 10:45" },
        { id: 4, time: "10:55 - 11:40" },
        { id: 5, time: "11:50 - 12:35" },
        { id: 6, time: "12:45 - 13:30" },
        { id: 7, time: "13:40 - 14:25" },
        { id: 8, time: "14:35 - 15:20" },
        { id: 9, time: "15:30 - 16:15" }
    ],
    days: [
        { id: 1, name: "Pondělí", short: "Po" },
        { id: 2, name: "Úterý", short: "Út" },
        { id: 3, name: "Středa", short: "St" },
        { id: 4, name: "Čtvrtek", short: "Čt" },
        { id: 5, name: "Pátek", short: "Pá" }
    ],
    lessons: [
        // === TýDEN A ===
        // Po
        { week: "A", day: 1, period: 1, duration: 2, subject: "OPS", teacher: "NILE", room: "U52", group: "SKP2" },
        { week: "A", day: 1, period: 2, duration: 1, subject: "ANJ", teacher: "MEMA", room: "U02", group: "SKP1" },
        { week: "A", day: 1, period: 3, duration: 1, subject: "TEV", teacher: "KRON", room: "uHALA", group: "SKP2" },
        { week: "A", day: 1, period: 3, duration: 1, subject: "TEV", teacher: "PLJI", room: "xCVIC", group: "SKP1" },
        { week: "A", day: 1, period: 4, duration: 1, subject: "POS", teacher: "SAJA", room: "U54", group: "SITE" },
        { week: "A", day: 1, period: 5, duration: 1, subject: "MAT", teacher: "PEIV", room: "U35", group: "ALL" },
        { week: "A", day: 1, period: 6, duration: 1, subject: "POS", teacher: "SAJA", room: "U54", group: "SITE" },
        { week: "A", day: 1, period: 6, duration: 1, subject: "POS", teacher: "JIMI", room: "U20", group: "PROG1" },
        { week: "A", day: 1, period: 6, duration: 2, subject: "AUT", teacher: "PEPE", room: "U53", group: "AUTO" },
        { week: "A", day: 1, period: 6, duration: 2, subject: "PAD", teacher: "HRLE", room: "U41", group: "PROG3" },
        { week: "A", day: 1, period: 6, duration: 2, subject: "POS", teacher: "CEFI", room: "U52", group: "GRAF1" },
        { week: "A", day: 1, period: 8, duration: 2, subject: "CIAn", teacher: "SAJA", room: "U59", group: "cisco" },
        // Ut
        { week: "A", day: 2, period: 1, duration: 1, subject: "TVY", teacher: "PEIV", room: "U60", group: "ALL" },
        { week: "A", day: 2, period: 2, duration: 1, subject: "OBN", teacher: "MALU", room: "U30", group: "ALL" },
        { week: "A", day: 2, period: 3, duration: 1, subject: "CJL", teacher: "GAMA", room: "U07", group: "ALL" },
        { week: "A", day: 2, period: 4, duration: 1, subject: "MSEm", teacher: "PEIV", room: "U33", group: "MSEm" },
        { week: "A", day: 2, period: 4, duration: 1, subject: "MSEa", teacher: "MEMA", room: "U11", group: "MSEa1" },
        { week: "A", day: 2, period: 4, duration: 1, subject: "MSEa", teacher: "VIJA", room: "U23", group: "MSEa2" },
        { week: "A", day: 2, period: 5, duration: 2, subject: "PAD", teacher: "HRLE", room: "U58", group: "PROG2" },
        { week: "A", day: 2, period: 5, duration: 2, subject: "PAD", teacher: "HOLC", room: "U40", group: "PROG1" },
        { week: "A", day: 2, period: 6, duration: 2, subject: "POS", teacher: "RAAL", room: "U55", group: "SITE" },
        { week: "A", day: 2, period: 6, duration: 2, subject: "AUT", teacher: "PEPE", room: "U53", group: "AUTO" },
        { week: "A", day: 2, period: 6, duration: 2, subject: "GRW", teacher: "NILE", room: "U47", group: "GRAF1" },
        { week: "A", day: 2, period: 6, duration: 1, subject: "POS", teacher: "JIMI", room: "U54", group: "PROG3" },
        { week: "A", day: 2, period: 8, duration: 1, subject: "TEV", teacher: "KRON", room: "uTEL", group: "SKP2" },
        { week: "A", day: 2, period: 8, duration: 1, subject: "TEV", teacher: "PLJI", room: "xCVIC", group: "SKP1" },
        // St
        { week: "A", day: 3, period: 0, duration: 2, subject: "PAD", teacher: "CATO", room: "U39", group: "PROG2" },
        { week: "A", day: 3, period: 0, duration: 2, subject: "PAD", teacher: "HOLC", room: "U08", group: "PROG3" },
        { week: "A", day: 3, period: 2, duration: 1, subject: "MSEm", teacher: "PEIV", room: "U30", group: "MSEm" },
        { week: "A", day: 3, period: 2, duration: 1, subject: "MSEa", teacher: "MEMA", room: "U11", group: "MSEa1" },
        { week: "A", day: 3, period: 2, duration: 1, subject: "MSEa", teacher: "VIJA", room: "U23", group: "MSEa2" },
        { week: "A", day: 3, period: 3, duration: 1, subject: "EKO", teacher: "SMDA", room: "U20", group: "ALL" },
        { week: "A", day: 3, period: 4, duration: 2, subject: "PAD", teacher: "HRLE", room: "U40", group: "PROG1" },
        { week: "A", day: 3, period: 4, duration: 2, subject: "PAD", teacher: "HOLC", room: "U39", group: "PROG2" },
        { week: "A", day: 3, period: 4, duration: 2, subject: "GRW", teacher: "VYTO", room: "U43", group: "GRAF1" },
        { week: "A", day: 3, period: 4, duration: 4, subject: "POS", teacher: "SAJA", room: "U54", group: "SITE" },
        { week: "A", day: 3, period: 4, duration: 2, subject: "AUT", teacher: "PEPE", room: "U53", group: "AUTO" },
        { week: "A", day: 3, period: 4, duration: 2, subject: "PAD", teacher: "CATO", room: "U58", group: "PROG3" },
        { week: "A", day: 3, period: 6, duration: 2, subject: "PAD", teacher: "CATO", room: "U40", group: "PROG1" },
        { week: "A", day: 3, period: 6, duration: 2, subject: "POS", teacher: "CEFI", room: "U56", group: "AUTO" },
        { week: "A", day: 3, period: 7, duration: 2, subject: "GRW", teacher: "KODA", room: "U43", group: "GRAF1" },
        { week: "A", day: 3, period: 8, duration: 2, subject: "POS", teacher: "JIMI", room: "U56", group: "PROG3" },
        // Ct
        { week: "A", day: 4, period: 1, duration: 1, subject: "OBN", teacher: "MALU", room: "U36", group: "ALL" },
        { week: "A", day: 4, period: 2, duration: 1, subject: "MAT", teacher: "PEIV", room: "U44", group: "ALL" },
        { week: "A", day: 4, period: 3, duration: 1, subject: "CJL", teacher: "GAMA", room: "U22", group: "ALL" },
        { week: "A", day: 4, period: 4, duration: 1, subject: "TVY", teacher: "PEIV", room: "U12", group: "ALL" },
        { week: "A", day: 4, period: 5, duration: 2, subject: "OPS", teacher: "NILE", room: "U54", group: "SKP1" },
        { week: "A", day: 4, period: 6, duration: 1, subject: "ANJ", teacher: "CHAI", room: "U05", group: "SKP2" },
        { week: "A", day: 4, period: 7, duration: 1, subject: "ANJ", teacher: "MEMA", room: "U21", group: "SKP1" },
        { week: "A", day: 4, period: 7, duration: 1, subject: "ANJ", teacher: "CHAI", room: "U15", group: "SKP2" },
        // Pa
        { week: "A", day: 5, period: 1, duration: 1, subject: "CJL", teacher: "GAMA", room: "U35", group: "ALL" },
        { week: "A", day: 5, period: 2, duration: 1, subject: "NEJ", teacher: "GAIV", room: "U10", group: "NEJ1" },
        { week: "A", day: 5, period: 2, duration: 1, subject: "NEJ", teacher: "RYLU", room: "U24", group: "NEJ2" },
        { week: "A", day: 5, period: 3, duration: 1, subject: "EKO", teacher: "SMDA", room: "U44", group: "ALL" },
        { week: "A", day: 5, period: 4, duration: 2, subject: "PRCv", teacher: "RAAL", room: "U53", group: "PRC1" },
        { week: "A", day: 5, period: 4, duration: 2, subject: "PRCv", teacher: "DUPE", room: "U56", group: "PRC2" },
        { week: "A", day: 5, period: 6, duration: 1, subject: "ANJ", teacher: "CHAI", room: "U29", group: "SKP2" },
        { week: "A", day: 5, period: 7, duration: 1, subject: "ANJ", teacher: "MEMA", room: "U23", group: "SKP1" },

        // === TýDEN B ===
        // Po
        { week: "B", day: 1, period: 0, duration: 2, subject: "ZTD", teacher: "SMDA", room: "U56", group: "SKP1" },
        { week: "B", day: 1, period: 1, duration: 2, subject: "OPS", teacher: "NILE", room: "U52", group: "SKP2" },
        { week: "B", day: 1, period: 2, duration: 1, subject: "ANJ", teacher: "MEMA", room: "U02", group: "SKP1" },
        { week: "B", day: 1, period: 3, duration: 1, subject: "TEV", teacher: "KRON", room: "uHALA", group: "SKP2" },
        { week: "B", day: 1, period: 3, duration: 1, subject: "TEV", teacher: "PLJI", room: "xCVIC", group: "SKP1" },
        { week: "B", day: 1, period: 4, duration: 1, subject: "POS", teacher: "SAJA", room: "U54", group: "SITE" },
        { week: "B", day: 1, period: 5, duration: 1, subject: "MAT", teacher: "PEIV", room: "U35", group: "ALL" },
        { week: "B", day: 1, period: 6, duration: 1, subject: "POS", teacher: "SAJA", room: "U54", group: "SITE" },
        { week: "B", day: 1, period: 6, duration: 1, subject: "POS", teacher: "JIMI", room: "U20", group: "PROG1" },
        { week: "B", day: 1, period: 6, duration: 2, subject: "AUT", teacher: "PEPE", room: "U53", group: "AUTO" },
        { week: "B", day: 1, period: 6, duration: 2, subject: "PAD", teacher: "HRLE", room: "U41", group: "PROG3" },
        { week: "B", day: 1, period: 6, duration: 2, subject: "POS", teacher: "CEFI", room: "U52", group: "GRAF1" },
        { week: "B", day: 1, period: 7, duration: 2, subject: "POS", teacher: "JIMI", room: "U56", group: "PROG1" },
        // Ut
        { week: "B", day: 2, period: 1, duration: 1, subject: "TVY", teacher: "PEIV", room: "U60", group: "ALL" },
        { week: "B", day: 2, period: 2, duration: 1, subject: "OBN", teacher: "MALU", room: "U30", group: "ALL" },
        { week: "B", day: 2, period: 3, duration: 1, subject: "CJL", teacher: "GAMA", room: "U07", group: "ALL" },
        { week: "B", day: 2, period: 4, duration: 1, subject: "MSEm", teacher: "PEIV", room: "U33", group: "MSEm" },
        { week: "B", day: 2, period: 4, duration: 1, subject: "MSEa", teacher: "MEMA", room: "U11", group: "MSEa1" },
        { week: "B", day: 2, period: 4, duration: 1, subject: "MSEa", teacher: "VIJA", room: "U23", group: "MSEa2" },
        { week: "B", day: 2, period: 5, duration: 2, subject: "PAD", teacher: "HRLE", room: "U58", group: "PROG2" },
        { week: "B", day: 2, period: 5, duration: 2, subject: "PAD", teacher: "HOLC", room: "U40", group: "PROG1" },
        { week: "B", day: 2, period: 6, duration: 2, subject: "POS", teacher: "RAAL", room: "U55", group: "SITE" },
        { week: "B", day: 2, period: 6, duration: 2, subject: "AUT", teacher: "PEPE", room: "U53", group: "AUTO" },
        { week: "B", day: 2, period: 6, duration: 2, subject: "GRW", teacher: "NILE", room: "U47", group: "GRAF1" },
        { week: "B", day: 2, period: 6, duration: 1, subject: "POS", teacher: "JIMI", room: "U54", group: "PROG3" },
        { week: "B", day: 2, period: 8, duration: 1, subject: "TEV", teacher: "KRON", room: "uTEL", group: "SKP2" },
        { week: "B", day: 2, period: 8, duration: 1, subject: "TEV", teacher: "PLJI", room: "xCVIC", group: "SKP1" },
        // St
        { week: "B", day: 3, period: 0, duration: 2, subject: "PAD", teacher: "CATO", room: "U39", group: "PROG2" },
        { week: "B", day: 3, period: 0, duration: 2, subject: "PAD", teacher: "HOLC", room: "U08", group: "PROG3" },
        { week: "B", day: 3, period: 2, duration: 1, subject: "MSEm", teacher: "PEIV", room: "U30", group: "MSEm" },
        { week: "B", day: 3, period: 2, duration: 1, subject: "MSEa", teacher: "MEMA", room: "U11", group: "MSEa1" },
        { week: "B", day: 3, period: 2, duration: 1, subject: "MSEa", teacher: "VIJA", room: "U23", group: "MSEa2" },
        { week: "B", day: 3, period: 3, duration: 1, subject: "EKO", teacher: "SMDA", room: "U20", group: "ALL" },
        { week: "B", day: 3, period: 4, duration: 2, subject: "PAD", teacher: "HRLE", room: "U40", group: "PROG1" },
        { week: "B", day: 3, period: 4, duration: 2, subject: "PAD", teacher: "HOLC", room: "U39", group: "PROG2" },
        { week: "B", day: 3, period: 4, duration: 2, subject: "GRW", teacher: "VYTO", room: "U43", group: "GRAF1" },
        { week: "B", day: 3, period: 4, duration: 4, subject: "POS", teacher: "SAJA", room: "U54", group: "SITE" },
        { week: "B", day: 3, period: 4, duration: 2, subject: "AUT", teacher: "PEPE", room: "U53", group: "AUTO" },
        { week: "B", day: 3, period: 4, duration: 2, subject: "PAD", teacher: "CATO", room: "U58", group: "PROG3" },
        { week: "B", day: 3, period: 6, duration: 2, subject: "PAD", teacher: "CATO", room: "U40", group: "PROG1" },
        { week: "B", day: 3, period: 6, duration: 2, subject: "POS", teacher: "CEFI", room: "U56", group: "AUTO" },
        { week: "B", day: 3, period: 7, duration: 2, subject: "GRW", teacher: "KODA", room: "U43", group: "GRAF1" },
        { week: "B", day: 3, period: 8, duration: 2, subject: "POS", teacher: "JIMI", room: "U56", group: "PROG2" },
        // Ct
        { week: "B", day: 4, period: 1, duration: 1, subject: "OBN", teacher: "MALU", room: "U36", group: "ALL" },
        { week: "B", day: 4, period: 2, duration: 1, subject: "MAT", teacher: "PEIV", room: "U44", group: "ALL" },
        { week: "B", day: 4, period: 3, duration: 1, subject: "CJL", teacher: "GAMA", room: "U22", group: "ALL" },
        { week: "B", day: 4, period: 4, duration: 1, subject: "TVY", teacher: "PEIV", room: "U12", group: "ALL" },
        { week: "B", day: 4, period: 5, duration: 2, subject: "OPS", teacher: "NILE", room: "U54", group: "SKP1" },
        { week: "B", day: 4, period: 6, duration: 1, subject: "ANJ", teacher: "CHAI", room: "U05", group: "SKP2" },
        { week: "B", day: 4, period: 7, duration: 1, subject: "ANJ", teacher: "MEMA", room: "U21", group: "SKP1" },
        { week: "B", day: 4, period: 7, duration: 1, subject: "ANJ", teacher: "CHAI", room: "U15", group: "SKP2" },
        { week: "B", day: 4, period: 8, duration: 2, subject: "ZTD", teacher: "SMDA", room: "U08", group: "SKP2" },
        // Pa
        { week: "B", day: 5, period: 1, duration: 1, subject: "CJL", teacher: "GAMA", room: "U35", group: "ALL" },
        { week: "B", day: 5, period: 2, duration: 1, subject: "NEJ", teacher: "GAIV", room: "U10", group: "NEJ1" },
        { week: "B", day: 5, period: 2, duration: 1, subject: "NEJ", teacher: "RYLU", room: "U24", group: "NEJ2" },
        { week: "B", day: 5, period: 3, duration: 1, subject: "EKO", teacher: "SMDA", room: "U44", group: "ALL" },
        { week: "B", day: 5, period: 4, duration: 2, subject: "PRCv", teacher: "RAAL", room: "U53", group: "PRC1" },
        { week: "B", day: 5, period: 4, duration: 2, subject: "PRCv", teacher: "DUPE", room: "U56", group: "PRC2" },
        { week: "B", day: 5, period: 6, duration: 1, subject: "ANJ", teacher: "CHAI", room: "U29", group: "SKP2" },
        { week: "B", day: 5, period: 7, duration: 1, subject: "ANJ", teacher: "MEMA", room: "U23", group: "SKP1" },

    ]
};
